### ISSUE TITLE
API Point 하나 추가요청!!!

### ISSUE THREAD

**Issue by hyeoktae** [final-project-fastflix/WPS#14]
앱에서만 사용하는 request가 하나 추가되야 할 거 같아요

동그란 이미지를 사용해요

미리보기인데 이거는 따로 관리 해야할거 같아서요

PreviewCellRequest

필요한 데이터 :
[Movie ID, circle image, logo image, videoFile, verticalSampleVideoFile]

10개정도면 충분할거 같네요. 

----------------------------------

전체 영화 필드에
Vertical sample video file 이 필요합니다. 
추가 부탁드릴게요.

**Comment by sug5806** [comment]
어허헣 빠르게 해보겠쑵니다

**Comment by sug5806** [comment]
필드명 추가 및 요청 API 뷰 추가
