### ISSUE TITLE
로그인 api body data

### ISSUE THREAD

**Issue by Sub2n** [final-project-fastflix/WPS#15]
아까는 raw data
![image](https://user-images.githubusercontent.com/48080762/61533034-a4378980-aa66-11e9-96ae-0a4fa98a2ee3.png)
이 형식으로 해도 됐었는데 지금은 form-data로 보내야지만 Token이 와요..
raw data도 되게 해주시면 안될까요 ㅎㅎ...

**Comment by hyeoktae** [comment]
동수님이 이 이슈를 싫어합니다. + 1

**Comment by Sub2n** [comment]
^^
그리고 아까 배열로 넣는 거 프로필 등록 API 문서에 Request랑 Response 예시 부탁드립니다

**Comment by Sub2n** [comment]
body raw data는 안 해주셔도 될 것 같아요!! 죄송합니다 이슈쓰는거재밌네요.... 프로필 여러개 등록하는 API 설명만 부탁드릴게요

**Comment by sug5806** [comment]
어허헣 빠르게 해보겠쑵니다

**Comment by sug5806** [comment]
API 문서 수정 완료
